Update LXC Build.yml

diff --git a/.github/workflows/LXC Build.yml b/.github/workflows/LXC Build.yml
--- a/.github/workflows/LXC Build.yml
+++ b/.github/workflows/LXC Build.yml
@@ -89,31 +89,30 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/kernel
           
-          # 克隆并应用 LXC 适配
-          git clone https://github.com/tomxi1997/lxc-docker-support-for-android.git utils
-          
-          # 注入 Kconfig 
-          [ -f "Kconfig" ] && echo 'source "utils/Kconfig"' >> "Kconfig"
-          
-          # 配置 defconfig
           CONFIG_PATH="arch/arm64/configs/${{ github.event.inputs.KERNEL_DEFCONFIG }}"
-          echo "CONFIG_DOCKER=y" >> "$CONFIG_PATH"
-          echo "CONFIG_VLAN_8021Q=m" >> "$CONFIG_PATH"
-          sed -i '/CONFIG_ANDROID_PARANOID_NETWORK/d' "$CONFIG_PATH"
-          echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> "$CONFIG_PATH"
+          echo "CONFIG_NET_NS=y" >> "$CONFIG_PATH"
+
+          echo "CONFIG_PID_NS=y" >> "$CONFIG_PATH"
+
+          echo "CONFIG_IPC_NS=y" >> "$CONFIG_PATH"
+
+     #     echo "CONFIG_DOCKER=y" >> "$CONFIG_PATH"
+     #     echo "CONFIG_VLAN_8021Q=m" >> "$CONFIG_PATH"
+      #    sed -i '/CONFIG_ANDROID_PARANOID_NETWORK/d' "$CONFIG_PATH"
+      #    echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> "$CONFIG_PATH"
           
           # 应用 runc/cgroup 补丁
-          chmod +x utils/runcpatch.sh
-          if [ -f "kernel/cgroup/cgroup.c" ]; then
-              sh utils/runcpatch.sh kernel/cgroup/cgroup.c
-          elif [ -f "kernel/cgroup.c" ]; then
-              sh utils/runcpatch.sh kernel/cgroup.c
-          fi
+    #      chmod +x utils/runcpatch.sh
+     #     if [ -f "kernel/cgroup/cgroup.c" ]; then
+     # #        sh utils/runcpatch.sh kernel/cgroup/cgroup.c
+      #    elif [ -f "kernel/cgroup.c" ]; then
+      #        sh utils/runcpatch.sh kernel/cgroup.c
+      #    fi
           
           # 应用网络补丁 (不报错则继续)
-          if [ -f "net/netfilter/xt_qtaguid.c" ]; then
-              patch -p1 < utils/xt_qtaguid.patch || echo "Patch failed, checking context..."
-          fi
+      #    if [ -f "net/netfilter/xt_qtaguid.c" ]; then
+       #       patch -p1 < utils/xt_qtaguid.patch || echo "Patch failed, checking context..."
+       #   fi
 
       - name: Make kernel
         run: |
